### ISSUE TITLE
support multiple value for one style in UIDLElementNode?

### ISSUE THREAD

**Issue by MurakamiKennzo** [teleporthq/teleport-code-generators#761]
Hi, thanks for the project, I'm happy to using it in my project, but currently, I find some problems.

I wanna generate css varibles, but there are some limits for me.

like this:

```json
{
  "name": "Token Simple",
  "node": {
    "type": "element",
    "content": {
      "elementType": "container",
      "style": {
        "margin": {
          "type": "dynamic",
          "content": {
            "referenceType": "token",
            "id": "space-2"
          }
        }
      },
      "children": []
    }
  }
}
```
the uidl will generate a style like this:
```css
.container {
  margin: var(--space-2);
}
```

It's great!😀

But, I wanna a style like this:
```css
.container {
  margin: var(--space-2) var(--space-4);
}
```

what should I do? currently it may not  support.

help wanted, Thanks!🥰
